spring:
  application:
    name: zuul-server
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    gallery-service:
      path: /gallery/**
      service-id: gallery-service
    image-service:
      path: /images/**
      service-id: image-service
    auth-service:
      path: /auth/**
      service-id: AUTH-SERVICE
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
